use_frameworks!

platform :ios, '9.0'

target 'lsj-EnlargeEdge_Example' do
  pod 'lsj-EnlargeEdge', :path => '../'

  target 'lsj-EnlargeEdge_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
